behaviors:
  Carolinensis:
    trainer_type: ppo           # PPO 사용
    max_steps: 5.0e6            # 총 학습 step
    time_horizon: 150            # 에피소드 단위 업데이트 간격
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 5000
    threaded: true

    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple   # 시각 관찰 필요 없으면 simple

    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0

#    behavioral_cloning:
#      demo_path: null

    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 150
    summary_freq: 10000
  Sagrei:
    trainer_type: ppo           # PPO 사용
    max_steps: 5.0e6            # 총 학습 step
    time_horizon: 150            # 에피소드 단위 업데이트 간격
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 5000
    threaded: true

    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple   # 시각 관찰 필요 없으면 simple

    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0

#    behavioral_cloning:
#      demo_path: null

    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 150
    summary_freq: 10000

