behaviors:
  WFCAgent:
    trainer_type: ppo
    
    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        
    max_steps: 2000000
    time_horizon: 1000
    summary_freq: 10000
    
    keep_checkpoints: 5
    checkpoint_interval: 50000

env_settings:
  env_path: null
  base_port: 5005
  num_envs: 1
  seed: -1
  
engine_settings:
  width: 1280
  height: 720
  quality_level: 0
  time_scale: 20.0
  target_frame_rate: -1
  no_graphics: false
